model:
  name: 'MinkUNet34'
  in_feat_size: 1
  out_classes: 5
  ignore_label: -1

source_dataset:
  name: 'WhuALS'
  dataset_path: '/root/data/whu_als'
  mapping_path: '/root/PC_DA/core/datasets/mapping_cfg/whu-als.yaml'

  voxel_size: 0.2
  use_intensity: False

  sub_numpts: 160000

  augmentation:
    z_rotate: True

  balance_weights: False

dataloader:
  batch_size: 6
  num_workers: 0

pipeline:
  epochs: 300
  gpus: 0
  seed: 1234
  validate: True
  resume: ''
  criterion: 'SoftDICELoss'

  optimizer_name: 'SGD'

  optimizer_SGD: 
    lr: 0.1
    momentum: 0.98
    weight_decay: 0.0001

  scheduler: 'ExponentialLR'

OUTPUT_DIR: 'results/src_WhuALS_MinkUnet34'

